"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StoreKeys = void 0;
var StoreKeys;
(function (StoreKeys) {
  StoreKeys["VERSION"] = "version";
  StoreKeys["HAS_RECENTLY_LAUNCHED"] = "hasRecentlyLaunched";
  StoreKeys["UUID"] = "uuid";
  StoreKeys["WINDOW_DIMENSIONS"] = "windowDimensions";
  StoreKeys["WINDOW_POSITION"] = "windowPosition";
  StoreKeys["MOD_FEATURES"] = "modFeatures";
  StoreKeys["DISPLAY_MAX_FPS"] = "displayMaxFps";
  StoreKeys["IS_DEVTOOLS_ENABLED"] = "enableDevTools";
  StoreKeys["ENABLE_YNISON_REMOTE_CONTROL"] = "enableYnisonRemoteControl";
  StoreKeys["ENABLE_AUTO_UPDATES"] = "enableAutoUpdates";
  StoreKeys["DEFAULT_EXPERIMENT_OVERRIDES"] = "defaultExperimentOverrides";
  StoreKeys["DEVICE_ID"] = "deviceId";
  StoreKeys["DEVICE_SOFTWARE_REVISION"] = "deviceSoftwareRevision";
  StoreKeys["DEVICE_CPU_REVISION"] = "deviceCpuRevision";
  StoreKeys["TRACKS_AVAILABILITY_UPDATED_AT"] = "tracksAvailabilityUpdatedAt";
  StoreKeys["REPOSITORY_META_UPDATED_AT"] = "repositoryMetaUpdatedAt";
})(StoreKeys || (exports.StoreKeys = StoreKeys = {}));
