"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Events = void 0;
var Events;
(function (Events) {
    Events["WINDOW_MINIMIZE"] = "WINDOW_MINIMIZE";
    Events["WINDOW_MAXIMIZE"] = "WINDOW_MAXIMIZE";
    Events["WINDOW_CLOSE"] = "WINDOW_CLOSE";
    Events["ON_UPDATE_INSTALL"] = "ON_UPDATE_INSTALL";
    Events["ON_UPDATE_AVAILABLE"] = "ON_UPDATE_AVAILABLE";
    Events["ON_APPLICATION_READY"] = "ON_APPLICATION_READY";
    Events["GET_PASSPORT_LOGIN"] = "GET_PASSPORT_LOGIN";
    Events["SHOW_RELEASE_NOTES"] = "SHOW_RELEASE_NOTES";
    Events["NEED_SHOW_RELEASE_NOTES"] = "NEED_SHOW_RELEASE_NOTES";
    Events["UPDATE_APPLICATION_DATA"] = "UPDATE_APPLICATION_DATA";
    Events["ON_PLAYER_STATE"] = "ON_PLAYER_STATE";
    Events["ON_HANDLE_DEEPLINK"] = "ON_HANDLE_DEEPLINK";
    Events["FIRST_LAUNCH"] = "FIRST_LAUNCH";
    Events["APPLICATION_THEME"] = "APPLICATION_THEME";
})(Events || (exports.Events = Events = {}));
